# filepath: /Users/rodrigomontenegro/Desktop/moreti2/BecaUV/backend/Dockerfile
FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]