@api = http://localhost:4000/alumnos
@api2 = http://localhost:4000/casinos
@api3 = http://localhost:4000/canjes

@api4 = http://localhost:4000/login

@api5 = http://localhost:4000/admin

GET {{api}}

###
GET {{api}}/2

###
POST {{api}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "rut": "15331246-k",
    "cantidad": 25,
    "fecha": "03-11-2022"
}

###
DELETE {{api}}/14

###
PUT {{api}}/2
Content-Type: application/json

{
    "nombre": "pedro",
    "rut": "3988675-3",
    "cantidad": 25,
    "fecha": "2022-03-04"
}

###
GET {{api2}}

###
POST {{api2}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "cantidad": 25
}

###
DELETE {{api2}}/7

###
GET {{api3}}/17760740-1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluaXN0cmFkb3IgICIsImlhdCI6MTcwMDUwMDkwNywiZXhwIjoxNzAwNTA0NTA3fQ.2EykRLALcMj5NUikJM-hUINl7DxgRmYn0U5M_fjK_UE

###
PATCH {{api3}}/17760740-1

###
POST {{api4}}/Pedro

###
POST {{api5}}
Content-Type: application/json
Authorization: BecasUVSecretKey

{
    "usuario": "Admin",
    "password": "12345",
    "role": "admin",
    "casino": "sin casino"
}