@api = http://localhost:4000/alumnos
@api2 = http://localhost:4000/casinos
@api3 = http://localhost:4000/canjes

GET {{api}}

###
GET {{api}}/2

###
POST {{api}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "rut": "15331246-k",
    "cantidad": 25,
    "fecha": "03-11-2022"
}

###
DELETE {{api}}/14

###
PUT {{api}}/2
Content-Type: application/json

{
    "nombre": "Katherine Valencia",
    "rut": "19061066-7",
    "cantidad": 25,
    "fecha": "2022-03-04"
}

###
GET {{api2}}

###
POST {{api2}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "cantidad": 25
}

###
DELETE {{api2}}/7

###
GET {{api3}}/17760740-1

###
PATCH {{api3}}/17760740-1